### ISSUE TITLE
Any plans to upgrade the project for the new rpi4B?

### ISSUE THREAD

**Issue by repcsi** [mkellsy/rpi-case-model#1]
Do you have any plans to upgrade the project for the new rpi4B? I desperately need a hackable case that I can use to install a pwm controllable fan, because the new rpi4B 4GB is running 10celsius hotter than the older rpi3B...

**Comment by mkellsy** [comment]
I have plans to update this. I need to get a 4B first for measurements. I'll hit up Micro Center this weekend and pick up a couple.

**Comment by repcsi** [comment]
Good to hear! Do you have any channels to receive support? I would like to support this effort!

**Comment by mkellsy** [comment]
I have tried to set up sponsoring, but they require me to have 100+ stars on the repository.

Good news is the 3 and the 4 are not much different, so it shouldn't take me long.

**Comment by mkellsy** [comment]
Just ordered a pi 4. Will be here on Thursday.

**Comment by repcsi** [comment]
Cool, just keep in mind that the 4 runs way hotter than the 3 :) 
Paypal on your mail? :)

**Comment by mkellsy** [comment]
Yep mkellsy@gmail.com

**Comment by mkellsy** [comment]
Thank You!

**Comment by mkellsy** [comment]
I got the bases done! I will tackle the tops tomorrow.

**Comment by mkellsy** [comment]
Update: I did the initial print of the RPI4 case. There are some fitment issues, but overall it is pretty good.

NEXT STEP
- Adjust the fitment with the IO, the RPI4 is 0.5 - 1mm longer then the RPI3
- Adjust the USB-C slot - Top needs to be longer
- The board retainers need to be 0.5 - 1mm longer - board is a bit loose

**Comment by repcsi** [comment]
Nice, I could open the case file in fusion360 so this will be perfect!!! :)
How would you install a fan to the top, what would be the best solution?

**Comment by mkellsy** [comment]
The pi 4b case is  done. You can download the files here or from Thingverse. https://www.thingiverse.com/thing:3793664

**Comment by mkellsy** [comment]
Sorry this project was built with SolidWorks. Not compatible with Fusion 360.

There are tops with bolt patterns for 25, 30 and 40 mm fans. Just secure the fan with screws and run the wire inside the case and connect to the gpio pins.

**Comment by repcsi** [comment]
It was not a question, it was a statement :). I managed to open it in fusion360, it can convert solidworks projects. Thank you Michael! :)
